spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true

app:
  storage:
    connection-string: ${APP_STORAGE_CONNECTION_STRING}
    containers:
      test: zips

server:
  error:
    include-message: always
    include-binding-errors: always
